CREATE TABLE image(
    id INT PRIMARY KEY AUTO_INCREMENT,
    image_name VARCHAR (255) NOT NULL UNIQUE,
    ipaddr VARCHAR (20),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL
);