<div class="row">

    <div class="col-md-4 col-md-offset-4">
        <?php $form = $this->form;
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <div class="imagePreview"></div>
        <div class="input-group">
            <label class="input-group-btn">
                <span class="btn btn-primary">
                    画像を選択<?php echo $this->formRow($this->form->get('image')); ?>
                </span>
            </label>
        </div>
        <?php echo $this->formRow($this->form->get('submit')); ?>
        <?php echo $this->formRow($this->form->get('csrf')); ?>
        <?php echo $this->form()->closeTag($form); ?>
    </div>

</div>
<script>
    $(document).on('change', ':file', function() {
        var input = $(this);
        var files = !!this.files ? this.files : [];
        if (!files.length || !window.FileReader) return;
        if (/^image/.test(files[0].type)){
            var reader = new FileReader();
            reader.readAsDataURL(files[0]);
            reader.onloadend = function(){
                input.parent().parent().parent().prev('.imagePreview').css("background-image", "url("+this.result+")");
            }
        }
    });
</script>
<style>
.imagePreview {
    width: 100%;
    height: 180px;
    background-position: center center;
    background-size: cover;
    -webkit-box-shadow: 0 0 1px 1px rgba(0, 0, 0, .3);
    display: inline-block;
}
</style>
