<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <?php $form = $this->form;
      $form->prepare();
      echo $this->form()->openTag($form);
    ?>
    <div class="imagePreview"></div>
    <?php if( count($this->form->get('image')->getMessages()) > 0 ){ ?>
      <div class="alert alert-danger">
        画像ファイル（PNG JPEG 形式）を選択してください
      </div>
    <?php } ?>
    <div class="input-group">
      <label class="input-group-btn">
        <span class="btn btn-primary">
          画像を選択<?php echo $this->formElement($this->form->get('image')); ?>
        </span>
      </label>
      <input id="file-name" type="text" class="form-control" disabled />
    </div>
    <div class="form-group" style="margin-top: 10px">
      <div class="col-md-12">
        <?php echo $this->formElement($this->form->get('submit')); ?>
      </div>
    </div>
    <?php echo $this->formElement($this->form->get('csrf')); ?>
    <?php echo $this->form()->closeTag($form); ?>
  </div>

</div>
<script>
    $(document).on('change', ':file', function() {
        var files = !!this.files ? this.files : [];
        if (!files.length || !window.FileReader){
            return;
        }

        // 画像ファイル名を表示
        $('#file-name').val($(this).prop('files')[0].name);

        if (/^image/.test(files[0].type)){
            var reader = new FileReader();
            reader.readAsDataURL(files[0]);
            reader.onloadend = function(){
                $('.imagePreview').css("background-image", "url("+this.result+")");
            }
        }
    });
</script>

